FixArmorStandLag: true
DisableAllProtocolLib: false

tablist:
  header:
    - ""
    - "&4Spartan&3.tk"
    - ""
    - "&6Gaming"
    - ""
  footer:
    - ""
    - "&3%tps% tps — %players% players — %ping% ping — %uptime% uptime"
    - ""
    - "&7donate: http://spartanarchy.tk/""
    - ""
